---

- name: install deps
  apt:
    name: '{{ packages }}'
    state: present
  become: true
  vars:
    packages:
      - nfs-common

- name: mount NFS
  mount:
    fstype: nfs4
    name: "{{ item.where }}"
    opts: "{{ item.opts | default(nfs_mount_opts) }}"
    src: "{{ item.what }}"
    dump: "{{ item.dump | default(omit) }}"
    passno: "{{ item.passno | default(omit) }}"
    state: mounted
  with_items: "{{ nfs_share_mounts }}"
  become: true
